# Generated by Django 4.1.5 on 2023-01-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salaryandvacanciesperyearsprofessiontable',
            options={'verbose_name': 'Количество вакансий и зарплата по годам по профессии frontend - табличные данные', 'verbose_name_plural': 'Количество вакансий и зарплата по годам по профессии frontend - табличные данные'},
        ),
        migrations.AlterModelOptions(
            name='salarypercitytable',
            options={'verbose_name': 'Зарплата по городам - табличные значения', 'verbose_name_plural': 'Зарпалата по городам - табличные значения'},
        ),
        migrations.AlterModelOptions(
            name='salaryperyearsgraphics',
            options={'verbose_name': 'Заработная плата - графики', 'verbose_name_plural': 'Заработная плата - графики'},
        ),
        migrations.AlterModelOptions(
            name='vacanciespercitygraphics',
            options={'verbose_name': 'Количество вакансий по городам - графики', 'verbose_name_plural': 'Количество вакансий по городам - графики'},
        ),
        migrations.AlterModelOptions(
            name='vacanciespercitytable',
            options={'verbose_name': 'Количество вакансий по городам - табличные значения', 'verbose_name_plural': 'Количество вакансий по городам - табличные значения'},
        ),
        migrations.AlterField(
            model_name='salaryandvacanciesperyearsprofessiontable',
            name='average_salary',
            field=models.IntegerField(verbose_name='средняя заработная плата'),
        ),
        migrations.AlterField(
            model_name='salaryandvacanciesperyearsprofessiontable',
            name='average_salary_profession',
            field=models.IntegerField(verbose_name='средняя заработная плата-frontend'),
        ),
        migrations.AlterField(
            model_name='salaryandvacanciesperyearsprofessiontable',
            name='vacancies_count',
            field=models.IntegerField(verbose_name='количество вакансий'),
        ),
        migrations.AlterField(
            model_name='salaryandvacanciesperyearsprofessiontable',
            name='vacancies_count_profession',
            field=models.IntegerField(verbose_name='количество вакансий-frontend'),
        ),
        migrations.AlterField(
            model_name='salaryandvacanciesperyearsprofessiontable',
            name='year',
            field=models.IntegerField(verbose_name='год'),
        ),
        migrations.AlterField(
            model_name='salarypercitytable',
            name='city',
            field=models.CharField(max_length=255, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='salarypercitytable',
            name='salary',
            field=models.IntegerField(verbose_name='зарплата'),
        ),
        migrations.AlterField(
            model_name='salaryperyearsgraphics',
            name='photo',
            field=models.ImageField(upload_to='photo', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='salaryperyearsgraphics',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='vacanciespercitygraphics',
            name='photo',
            field=models.ImageField(upload_to='photo', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='vacanciespercitygraphics',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='vacanciespercitytable',
            name='city',
            field=models.CharField(max_length=255, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='vacanciespercitytable',
            name='vacancy_rate',
            field=models.IntegerField(verbose_name='количество вакансий'),
        ),
    ]
