# Generated by Django 4.1.5 on 2023-01-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_salaryandvacanciesperyearsprofessiontable_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacanciespercitytable',
            name='vacancy_rate',
            field=models.FloatField(verbose_name='количество вакансий'),
        ),
    ]
