# Generated by Django 4.1.5 on 2023-01-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_vacanciespercitytable_vacancy_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsPerYears',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='год')),
                ('first_vacancy', models.CharField(max_length=255, verbose_name='первый навык')),
                ('second_vacancy', models.CharField(max_length=255, verbose_name='второй навык')),
                ('third_vacancy', models.CharField(max_length=255, verbose_name='третий навык')),
                ('fourth_vacancy', models.CharField(max_length=255, verbose_name='четвертый навык')),
                ('fifth_vacancy', models.CharField(max_length=255, verbose_name='пятый навык')),
                ('sixth_vacancy', models.CharField(max_length=255, verbose_name='шестой навык')),
                ('seventh_vacancy', models.CharField(max_length=255, verbose_name='седьмой навык')),
                ('eighth_vacancy', models.CharField(max_length=255, verbose_name='восьмой навык')),
                ('ninth_vacancy', models.CharField(max_length=255, verbose_name='девятый навык')),
                ('tenth_vacancy', models.CharField(max_length=255, verbose_name='десятый навык')),
            ],
        ),
    ]
